from enum import Enum

class msg_type(Enum):
    MODEL_UPDATE_MSG = 'MODEL_UPDATE_MSG'
    MULTIPLE_UPDATE_MSG = 'MULTIPLE_UPDATE_MSG'
    METRICS_SNAPSHOT_MSG = 'METRICS_SNAPSHOT_MSG'
    OBJECTIVES_MSG = 'OBJECTIVES_MSG'
    TUNING_END_MSG = 'TUNING_END_MSG'
